### ISSUE TITLE
How to read selected option from dropdown in Golem v2?

### ISSUE THREAD

**Issue by sawsedge** [ProtoTest/ProtoTest.Golem#26]
Hi,

Is there a way, in Golem, to get the currently selection option in a dropdown (read the value)?

In bare selenium one can use the SelectedOption property of the SelectElement class.  

I have HTML that looks like:
`<select.... >
   <option>another option</option>
    <option selected>displayed text for option</option>
</select>`

thank you!

**Comment by bkitchener1** [comment]
There isn't a property or method that exposes this, but you can always use the actual WebElement, which is stored in the element property.  

  var someElement = new Element(By.Id("SomeId"));
  var webelement = someElement.WrappedElement;  //finds the element on this step
  var select = new SelectElement(webelement);
  var text = select.SelectedOption.Text;

I will post an update soon with some methods in the element class to handle this.

**Comment by sawsedge** [comment]
Thank you!
